# Generated by Django 4.2.6 on 2024-01-24 06:42

import api.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('ast_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='課題ID')),
                ('ast_limit', models.DateField(default=datetime.date(2024, 1, 24), null=True, verbose_name='期限')),
            ],
            options={
                'verbose_name': '課題',
                'verbose_name_plural': '課題',
            },
        ),
        migrations.CreateModel(
            name='AssignmentStatus',
            fields=[
                ('state_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='提出状況ID')),
                ('state_flg', models.BooleanField(default=False, verbose_name='提出状況')),
                ('state_ast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assignment', verbose_name='課題')),
                ('state_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '提出状況',
                'verbose_name_plural': '提出状況',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('time_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='時間割ID')),
                ('time_section', models.IntegerField(choices=[(0, '1限'), (1, '2限'), (2, '3限'), (3, '4限'), (4, '5限'), (5, '6限')], default=0, verbose_name='コマ')),
                ('time_day', models.IntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日')], default=0, verbose_name='曜日')),
            ],
            options={
                'verbose_name': '時間割',
                'verbose_name_plural': '時間割',
            },
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_grade',
            field=models.IntegerField(choices=[(0, '1年'), (1, '2年')], default=0, verbose_name='学年'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='教師'),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_classes',
            field=models.ForeignKey(on_delete=models.SET(api.models.get_sentinel_classes), to='api.classes', verbose_name='授業'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='ast_classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classes', verbose_name='授業'),
        ),
    ]
