# Generated by Django 4.2.6 on 2024-02-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assignmentstatus_state_res_alter_team_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='2024-02-06', verbose_name='チーム名'),
        ),
    ]
