# Generated by Django 4.2.6 on 2024-01-24 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_assignment_ast_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='ast_limit',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='期限'),
        ),
    ]
