# Generated by Django 4.2.6 on 2024-01-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_assignment_ast_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='time_grade',
            field=models.IntegerField(choices=[(0, '1年'), (1, '2年')], default=0, verbose_name='学年'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_section',
            field=models.IntegerField(choices=[(0, '1年'), (1, '2年')], default=0, verbose_name='コマ'),
        ),
    ]
