# Generated by Django 4.2.6 on 2024-02-08 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_message_message_date_alter_team_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='2024-02-08', verbose_name='チーム名'),
        ),
        migrations.CreateModel(
            name='TeamFile',
            fields=[
                ('file_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='チームファイルID')),
                ('file_name', models.TextField(verbose_name='ファイル名')),
                ('file_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_team', to='api.team', verbose_name='チーム')),
            ],
            options={
                'verbose_name': 'チームファイル',
                'verbose_name_plural': 'チームファイル',
            },
        ),
    ]
