# Generated by Django 4.2.6 on 2024-01-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_timetable_time_grade_alter_timetable_time_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='time_section',
            field=models.IntegerField(choices=[(0, '1限'), (1, '2限'), (2, '3限'), (3, '4限'), (4, '5限'), (5, '6限')], default=0, verbose_name='コマ'),
        ),
    ]
