# Generated by Django 4.2.6 on 2024-02-09 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_team_team_name_teamfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='2024-02-09', verbose_name='チーム名'),
        ),
        migrations.CreateModel(
            name='TeamLink',
            fields=[
                ('link_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='チームリンクID')),
                ('link_URL', models.TextField(verbose_name='リンク')),
                ('link_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_team', to='api.team', verbose_name='チーム')),
            ],
            options={
                'verbose_name': 'チームリンク',
                'verbose_name_plural': 'チームリンク',
            },
        ),
    ]
