# Generated by Django 4.2.6 on 2024-02-09 17:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_team_team_name_teamlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='likecategory',
            name='like_category',
            field=models.IntegerField(choices=[(0, 'ざっくり'), (1, 'ゲーム'), (2, '趣味'), (3, 'プログラミング'), (4, 'いきもの')], default=0, verbose_name='好きなものカテゴリ'),
        ),
        migrations.AlterField(
            model_name='likecategory',
            name='like_icon',
            field=models.ImageField(blank=True, default='icon/like/default_icon.png', null=True, upload_to=api.models.saveLikePath, verbose_name='アイコン'),
        ),
    ]
