# Generated by Django 4.2.6 on 2024-01-24 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_timetable_time_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='お知らせID')),
                ('notice_main', models.TextField(blank=True, max_length=2048, null=True, verbose_name='本文')),
                ('notice_date', models.DateField(auto_now=True, verbose_name='更新日時')),
                ('notice_classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classes', unique=True, verbose_name='授業')),
                ('notice_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
            },
        ),
        migrations.CreateModel(
            name='LinkClasses',
            fields=[
                ('link_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='リンクID')),
                ('link', models.TextField(default='https://yahoo.co.jp', max_length=500, verbose_name='URL')),
                ('link_name', models.TextField(default=models.TextField(default='https://yahoo.co.jp', max_length=500, verbose_name='URL'), verbose_name='リンク名')),
                ('link_date', models.DateField(auto_now_add=True, verbose_name='作成日時')),
                ('link_classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classes', verbose_name='授業')),
            ],
            options={
                'verbose_name': 'リンク',
                'verbose_name_plural': 'リンク',
            },
        ),
    ]
