# Generated by Django 4.2.6 on 2024-02-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_likecategory_like_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecategory',
            name='like_category',
            field=models.IntegerField(choices=[(0, 'ゲーム'), (1, '趣味'), (2, 'プログラミング'), (3, 'いきもの')], default=0, verbose_name='好きなものカテゴリ'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='2024-02-11', verbose_name='チーム名'),
        ),
    ]
