# Generated by Django 4.2.6 on 2024-01-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notice_linkclasses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classes', verbose_name='授業'),
        ),
    ]
