# Generated by Django 4.2.6 on 2024-02-14 18:18

import api.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_likecategory_like_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='2024-02-14', verbose_name='チーム名'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user_icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='icon/user/default_icon.png', force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to=api.models.savePath, verbose_name='アイコン'),
        ),
    ]
