# Generated by Django 4.2.6 on 2024-01-24 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_notice_notice_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='チームID')),
                ('team_grade', models.IntegerField(choices=[(0, '1年'), (1, '2年')], default=0, verbose_name='学年')),
                ('team_name', models.TextField(default='<function now at 0x7ff1069da050>', verbose_name='チーム名')),
            ],
            options={
                'verbose_name': 'チーム',
                'verbose_name_plural': 'チーム',
            },
        ),
        migrations.AlterField(
            model_name='linkclasses',
            name='link_name',
            field=models.TextField(default='', verbose_name='リンク名'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='メッセージID')),
                ('message', models.TextField(verbose_name='本文')),
                ('message_date', models.DateField(auto_now_add=True, verbose_name='投稿日時')),
                ('message_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team', verbose_name='チーム')),
                ('message_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'メッセージ',
                'verbose_name_plural': 'メッセージ',
            },
        ),
    ]
