# Generated by Django 4.2.6 on 2024-02-14 18:59

import api.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_team_team_name_alter_usertable_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='user_icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='icon/user/default_icon.webp', force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to=api.models.savePath, verbose_name='アイコン'),
        ),
    ]
