# Generated by Django 4.2.6 on 2024-01-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_likecategory_alter_team_team_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='<function now at 0x7fc893da6050>', verbose_name='チーム名'),
        ),
    ]
