# Generated by Django 4.2.6 on 2024-02-16 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_usertable_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentstatus',
            name='state_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='提出日時'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='2024-02-16', verbose_name='チーム名'),
        ),
    ]
