# Generated by Django 4.2.6 on 2024-02-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_assignmentstatus_state_date_alter_team_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlink',
            name='link_title',
            field=models.TextField(blank=True, null=True, verbose_name='リンク名'),
        ),
    ]
