# Generated by Django 4.2.6 on 2024-02-17 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_teamlink_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_admin',
            field=models.ForeignKey(default='akahane', on_delete=django.db.models.deletion.CASCADE, related_name='team_admin', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='2024-02-17', verbose_name='チーム名'),
        ),
    ]
