# Generated by Django 4.2.6 on 2024-02-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_team_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='<function now at 0x7f5a51df6050>', verbose_name='チーム名'),
        ),
    ]
