# Generated by Django 4.2.6 on 2024-02-20 10:01

import api.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_team_team_admin_alter_team_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecategory',
            name='like_icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='icon/like/default_icon.webp', force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to=api.models.saveLikePath, verbose_name='アイコン'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='2024-02-20', verbose_name='チーム名'),
        ),
    ]
