# Generated by Django 4.2.6 on 2024-02-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_likecategory_like_icon_alter_team_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecategory',
            name='like_name',
            field=models.TextField(unique=True, verbose_name='好きなもの名'),
        ),
    ]
