# Generated by Django 4.2.6 on 2024-02-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_likecategory_like_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeImage',
            fields=[
                ('image_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='おしらせ画像ID')),
                ('image_url', models.TextField(verbose_name='おしらせ画像URL')),
            ],
            options={
                'verbose_name': 'おしらせ画像',
                'verbose_name_plural': 'おしらせ画像',
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='2024-02-22', verbose_name='チーム名'),
        ),
    ]
