# Generated by Django 4.2.6 on 2024-02-05 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_team_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='<function now at 0x7f2ca44da050>', verbose_name='チーム名'),
        ),
    ]
