# Generated by Django 4.2.6 on 2024-02-05 15:39

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_notice_notice_user_alter_team_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='ast_classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ast_classes', to='api.classes', verbose_name='授業'),
        ),
        migrations.AlterField(
            model_name='assignmentstatus',
            name='state_ast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_ast', to='api.assignment', verbose_name='課題'),
        ),
        migrations.AlterField(
            model_name='assignmentstatus',
            name='state_std',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_std', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher', to=settings.AUTH_USER_MODEL, verbose_name='教師'),
        ),
        migrations.AlterField(
            model_name='likeuser',
            name='conf_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conf_like', to='api.likecategory', verbose_name='好きなもの'),
        ),
        migrations.AlterField(
            model_name='likeuser',
            name='conf_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conf_user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='linkclasses',
            name='link_classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_classes', to='api.classes', verbose_name='授業'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_team', to='api.team', verbose_name='チーム'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_classes', to='api.classes', verbose_name='授業'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_user', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='<function now at 0x7fd153a62050>', verbose_name='チーム名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_classes',
            field=models.ForeignKey(on_delete=models.SET(api.models.get_sentinel_classes), related_name='time_classes', to='api.classes', verbose_name='授業'),
        ),
    ]
