# Generated by Django 4.2.6 on 2024-02-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_noticeimage_alter_team_team_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticeImage',
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_main',
            field=models.TextField(blank=True, default='', max_length=2048, null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='2024-02-24', verbose_name='チーム名'),
        ),
    ]
