# Generated by Django 4.2.6 on 2024-02-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_assignment_ast_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ast_disc',
            field=models.TextField(blank=True, null=True, verbose_name='課題説明'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='ast_title',
            field=models.TextField(blank=True, null=True, verbose_name='課題名'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.TextField(default='<function now at 0x7efd1b832050>', verbose_name='チーム名'),
        ),
    ]
